<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Employee::create([
            'ci' => 9406795,
            'name' => 'Clever',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 5173226,
            'name' => 'Luis',
            'lastname' => 'Sandoval',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8037861,
            'name' => 'Edwin',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 9326584,
            'name' => 'Mauricio',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7993972,
            'name' => 'Gery',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 12552162,
            'name' => 'Gustavo',
            'lastname' => 'Quisbert Ventura',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 14263548,
            'name' => 'Enzo',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8697768,
            'name' => 'Angel',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8770492,
            'name' => 'Roger',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 11267379,
            'name' => 'Ernesto',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7046351,
            'name' => 'Armando',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7952877,
            'name' => 'Luis',
            'lastname' => 'Garey',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 5913978,
            'name' => 'Yazmin',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7928401,
            'name' => 'Jose',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 5733161,
            'name' => 'Pablo',
            'lastname' => 'Sandoval',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 9399947,
            'name' => 'Roscio',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8693177,
            'name' => 'Branlyn',
            'lastname' => 'Mamani',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7861796,
            'name' => 'Fabio',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8710140,
            'name' => 'Samuel',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 1,
            'name' => 'Isaias',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7861830,
            'name' => 'Ruben',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 11066520,
            'name' => 'Victor',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7979938,
            'name' => 'Alex',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 13750109,
            'name' => 'Abigail',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7964268,
            'name' => 'Sahian',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7238748,
            'name' => 'Brian',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 12681711,
            'name' => 'Vania',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 13749839,
            'name' => 'Joshua',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8848153,
            'name' => 'Osman',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7603856,
            'name' => 'Ricardo',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 9395042,
            'name' => 'Liz',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 14419459,
            'name' => 'Luis F',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7962772,
            'name' => 'Crismar',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 5224381,
            'name' => 'Ever',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8709868,
            'name' => 'Deymar',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 13895986,
            'name' => 'Estibem',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7936142,
            'name' => 'Andres',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 7330292,
            'name' => 'Diana',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 4386719,
            'name' => 'Veronica',
            'lastname' => 'null',
            'genero' => 'Femenino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 8694359,
            'name' => 'Felix',
            'lastname' => 'Mamani',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 4527202,
            'name' => 'Paolo',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
        Employee::create([
            'ci' => 2,
            'name' => 'Nadir',
            'lastname' => 'null',
            'genero' => 'Masculino',
            'dateNac' => '0000-00-00 00:00:00',
            'address' => 'Cochabamaba',
            'phone' => 'null',
            'estadoCivil' => 'Soltero',
            'area_trabajo_id' => 1,
            'puesto_trabajo_id' => 1,
            'contrato_id' => 1,
            'fechaInicio' => '2022-01-01 01:01:01',
            'image' => 'null',
        ]);
    }
}
